#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99

PROG="/usr/bin/hev-socks5-tunnel"
CONF="hev-socks5-tunnel"
HST_YML="/etc/hev-socks5-tunnel/main.yml"

start_service() {
    generate_config

    local enabled
    config_load "$CONF"
    config_get_bool enabled "config" "enabled" "0"
    [ "$enabled" = "1" ] || return 0

    procd_open_instance
    procd_set_param command " $PROG" "$HST_YML"
    procd_set_param file "$HST_YML"

    procd_set_param limits core="unlimited"
	procd_set_param limits nofile="1000000 1000000"
    procd_set_param stderr 1
    procd_set_param stdout 1
    procd_set_param respawn

    procd_close_instance
}

stop_service() {
    rm -f "$HST_YML"
}

service_triggers() {
    procd_add_config_trigger "$CONF"
}

generate_config() {
    local enabled
    config_load "$CONF"
    config_get_bool enabled "config" "enabled" "0"
    [ "$enabled" = "1" ] || return 0

    local \
        t_name t_mtu t_ipv4 t_ipv6 \
        s_addr s_port s_udp s_user s_pass \
        dns_en dns_addr dns_port dns_net dns_mask \
        log_lvl log_file

    config_get t_name main tunnel_name "tun0"
    config_get t_mtu main tunnel_mtu "8500"
    config_get t_ipv4 main tunnel_ipv4 "198.18.0.1"
    config_get t_ipv6 main tunnel_ipv6 "fc00::1"

    config_get s_addr main socks5_address "127.0.0.1"
    config_get s_port main socks5_port "1080"
    config_get s_udp main socks5_udp "udp"
    config_get s_user main socks5_username ""
    config_get s_pass main socks5_password ""

    config_get_bool dns_en main mapdns_enabled 0
    config_get dns_addr main mapdns_address "198.18.0.2"
    config_get dns_port main mapdns_port "53"
    config_get dns_net main mapdns_network "100.64.0.0"
    config_get dns_mask main mapdns_netmask "255.192.0.0"

    config_get log_lvl main log_level "warn"
    config_get log_file main log_file "stderr"

    # Ensure config directory exists
    mkdir -p "$(dirname "$HST_YML")"

    # Generate YAML config
    cat > "$HST_YML" <<EOF
tunnel:
  name: $t_name
  mtu: $t_mtu
  multi-queue: false
  ipv4: $t_ipv4
  ipv6: '$t_ipv6'

socks5:
  port: $s_port
  address: $s_addr
  udp: '$s_udp'
EOF

    # Optional authentication
    if [ -n "$s_user" ]; then
        echo "username: '$s_user'" >> "$HST_YML"
    fi
    if [ -n "$s_pass" ]; then
        echo "password: '$s_pass'" >> "$HST_YML"
    fi

    # Optional MapDNS
    if [ "$dns_en" = "1" ]; then
        cat >> "$HST_YML" <<EOF

mapdns:
  address: $dns_addr
  port: $dns_port
  network: $dns_net
  netmask: $dns_mask
EOF
    fi

    # Miscellaneous settings
    cat >> "$HST_YML" <<EOF

misc:
  log-file: $log_file
  log-level: $log_lvl
EOF

    chmod 600 "$HST_YML"
}

