#!/bin/sh
uci -q batch <<-EOF >/dev/null
    set hev-socks5-tunnel.config='hev-socks5-tunnel'
    set hev-socks5-tunnel.config.enabled='0'
    set hev-socks5-tunnel.config.tunnel_name='tun0'
    set hev-socks5-tunnel.config.tunnel_mtu='8500'
    set hev-socks5-tunnel.config.tunnel_ipv4='198.18.0.1'
    set hev-socks5-tunnel.config.tunnel_ipv6='fc00::1'
    set hev-socks5-tunnel.config.socks5_address='127.0.0.1'
    set hev-socks5-tunnel.config.socks5_port='1080'
    set hev-socks5-tunnel.config.socks5_udp='udp'
    set hev-socks5-tunnel.config.mapdns_enabled='0'
    set hev-socks5-tunnel.config.mapdns_address='198.18.0.2'
    set hev-socks5-tunnel.config.mapdns_port='53'
    set hev-socks5-tunnel.config.mapdns_network='100.64.0.0'
    set hev-socks5-tunnel.config.mapdns_netmask='255.192.0.0'
    set hev-socks5-tunnel.config.log_level='warn'
    set hev-socks5-tunnel.config.log_file='stderr'
    commit hev-socks5-tunnel
EOF
exit 0